config-version: 1

# List of reclaimable rewards.
# The order of rewards matters. The plugin will go from top to bottom of this list to find a reward for the player.
rewards:
  1:
    # The permission required to claim.
    permission: "reclaim.nothing"
    # The cooldown for this reward, in seconds.
    cooldown: 5
    # The slot of this item in the GUI.
    slot: 0
    # The material representing this reward in the GUI.
    material: "DIRT"
    # The amount of Vault currency the player will be given.
    money: 1
    # Items to give away.
    items:
      # The name of the material.
      DIRT:
        name: "&b&lSpecial Dirt"
        lore:
          - "&dA very special piece of dirt."
          - "&dGet this by using /reclaim!"
        # Enchantments to apply to the item.
        enchants:
          # The name of the enchantment, followed by the level.
          DURABILITY: 10
          PROTECTION_ENVIRONMENTAL: 20
    # List of commands to execute.
    commands:
      - "broadcast %player% has claimed a reward!"
